services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend_rds
      - backend_redis
    volumes:
      - ./frontend/templates:/usr/share/nginx/html
      - ./frontend/config.json:/usr/share/nginx/html/config.json

  backend_rds:
    build: ./backend_rds
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - "8000:8000"

  backend_redis:
    build: ./backend_redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - "8001:8001"
